//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace neoStockMaster.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("neoStockMaster.Languages.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        internal static string Ana_Menü {
            get {
                return ResourceManager.GetString("Ana Menü", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery.
        /// </summary>
        internal static string Bilgilerimi_Hatırlat {
            get {
                return ResourceManager.GetString("Bilgilerimi Hatırlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cii {
            get {
                object obj = ResourceManager.GetObject("cii", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string Çıkış_Yap {
            get {
                return ResourceManager.GetString("Çıkış Yap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cropped_tc_bayrak {
            get {
                object obj = ResourceManager.GetObject("cropped-tc-bayrak", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Dil {
            get {
                return ResourceManager.GetString("Dil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dollar.
        /// </summary>
        internal static string Dolar {
            get {
                return ResourceManager.GetString("Dolar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Rate Information.
        /// </summary>
        internal static string Döviz_Bilgisi {
            get {
                return ResourceManager.GetString("Döviz Bilgisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Email Address.
        /// </summary>
        internal static string E_Mail_Adresinizi_Yazınız {
            get {
                return ResourceManager.GetString("E-Mail Adresinizi Yazınız", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Ekle {
            get {
                return ResourceManager.GetString("Ekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English2 {
            get {
                return ResourceManager.GetString("English2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euro.
        /// </summary>
        internal static string Euro {
            get {
                return ResourceManager.GetString("Euro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        internal static string Excel_e_Aktar {
            get {
                return ResourceManager.GetString("Excel\'e Aktar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Fiyat {
            get {
                return ResourceManager.GetString("Fiyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Price - Add Order.
        /// </summary>
        internal static string Fiyat_Hesapla___Sipariş_Ekle {
            get {
                return ResourceManager.GetString("Fiyat Hesapla - Sipariş Ekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In Screen.
        /// </summary>
        internal static string Giriş_Ekranı {
            get {
                return ResourceManager.GetString("Giriş Ekranı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string Giriş_Yap {
            get {
                return ResourceManager.GetString("Giriş Yap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Remember.
        /// </summary>
        internal static string ID_Hatırla {
            get {
                return ResourceManager.GetString("ID Hatırla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string İsim {
            get {
                return ResourceManager.GetString("İsim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the Action.
        /// </summary>
        internal static string İşlemi_Seç {
            get {
                return ResourceManager.GetString("İşlemi Seç", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit Margin.
        /// </summary>
        internal static string Kâr_Yüzdesi {
            get {
                return ResourceManager.GetString("Kâr Yüzdesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Screen.
        /// </summary>
        internal static string Kayıt_Ekranı {
            get {
                return ResourceManager.GetString("Kayıt Ekranı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Kayıt_Ol {
            get {
                return ResourceManager.GetString("Kayıt Ol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Kod {
            get {
                return ResourceManager.GetString("Kod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information.
        /// </summary>
        internal static string Kullanıcı_Bilgileri {
            get {
                return ResourceManager.GetString("Kullanıcı Bilgileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Kullanıcı_İsmi {
            get {
                return ResourceManager.GetString("Kullanıcı İsmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Username.
        /// </summary>
        internal static string Kullanıcı_İsmini_Hatırlat {
            get {
                return ResourceManager.GetString("Kullanıcı İsmini Hatırlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Verification.
        /// </summary>
        internal static string Kullanıcı_Onaylama {
            get {
                return ResourceManager.GetString("Kullanıcı Onaylama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Password.
        /// </summary>
        internal static string Kullanıcı_Şifresi {
            get {
                return ResourceManager.GetString("Kullanıcı Şifresi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string Maliyet {
            get {
                return ResourceManager.GetString("Maliyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Onayla {
            get {
                return ResourceManager.GetString("Onayla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Şifre {
            get {
                return ResourceManager.GetString("Şifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Remember.
        /// </summary>
        internal static string Şifre_Hatırla {
            get {
                return ResourceManager.GetString("Şifre Hatırla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Password.
        /// </summary>
        internal static string Şifremi_Hatırlat {
            get {
                return ResourceManager.GetString("Şifremi Hatırlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View &amp; Edit Orders.
        /// </summary>
        internal static string Siparişleri_Görüntüle___Düzenle {
            get {
                return ResourceManager.GetString("Siparişleri Görüntüle - Düzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting.
        /// </summary>
        internal static string Sıralama {
            get {
                return ResourceManager.GetString("Sıralama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        internal static string Stok {
            get {
                return ResourceManager.GetString("Stok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Temizle {
            get {
                return ResourceManager.GetString("Temizle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        internal static string Türkçe {
            get {
                return ResourceManager.GetString("Türkçe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Information.
        /// </summary>
        internal static string Ürün_Bilgileri {
            get {
                return ResourceManager.GetString("Ürün Bilgileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Product.
        /// </summary>
        internal static string Ürün_Düzenle {
            get {
                return ResourceManager.GetString("Ürün Düzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product.
        /// </summary>
        internal static string Ürün_Ekle {
            get {
                return ResourceManager.GetString("Ürün Ekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Operations.
        /// </summary>
        internal static string Ürün_İşlemleri {
            get {
                return ResourceManager.GetString("Ürün İşlemleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string Ürünler {
            get {
                return ResourceManager.GetString("Ürünler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on Top.
        /// </summary>
        internal static string Uygulamayı_Üstte_Tut {
            get {
                return ResourceManager.GetString("Uygulamayı Üstte Tut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of Day Report.
        /// </summary>
        internal static string Z_Raporu {
            get {
                return ResourceManager.GetString("Z Raporu", resourceCulture);
            }
        }
    }
}
