//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace neoStockMaster.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("neoStockMaster.Languages.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery.
        /// </summary>
        internal static string Bilgilerimi_Hatırlat {
            get {
                return ResourceManager.GetString("Bilgilerimi Hatırlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Dil {
            get {
                return ResourceManager.GetString("Dil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Email Address.
        /// </summary>
        internal static string E_Mail_Adresinizi_Yazınız {
            get {
                return ResourceManager.GetString("E-Mail Adresinizi Yazınız", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In Screen.
        /// </summary>
        internal static string Giriş_Ekranı {
            get {
                return ResourceManager.GetString("Giriş Ekranı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string Giriş_Yap {
            get {
                return ResourceManager.GetString("Giriş Yap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Remember.
        /// </summary>
        internal static string ID_Hatırla {
            get {
                return ResourceManager.GetString("ID Hatırla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string İsim {
            get {
                return ResourceManager.GetString("İsim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the Action.
        /// </summary>
        internal static string İşlemi_Seç {
            get {
                return ResourceManager.GetString("İşlemi Seç", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Screen.
        /// </summary>
        internal static string Kayıt_Ekranı {
            get {
                return ResourceManager.GetString("Kayıt Ekranı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Kayıt_Ol {
            get {
                return ResourceManager.GetString("Kayıt Ol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Kod {
            get {
                return ResourceManager.GetString("Kod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information.
        /// </summary>
        internal static string Kullanıcı_Bilgileri {
            get {
                return ResourceManager.GetString("Kullanıcı Bilgileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Kullanıcı_İsmi {
            get {
                return ResourceManager.GetString("Kullanıcı İsmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Username.
        /// </summary>
        internal static string Kullanıcı_İsmini_Hatırlat {
            get {
                return ResourceManager.GetString("Kullanıcı İsmini Hatırlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Verification.
        /// </summary>
        internal static string Kullanıcı_Onaylama {
            get {
                return ResourceManager.GetString("Kullanıcı Onaylama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Password.
        /// </summary>
        internal static string Kullanıcı_Şifresi {
            get {
                return ResourceManager.GetString("Kullanıcı Şifresi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Onayla {
            get {
                return ResourceManager.GetString("Onayla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Şifre {
            get {
                return ResourceManager.GetString("Şifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Remember.
        /// </summary>
        internal static string Şifre_Hatırla {
            get {
                return ResourceManager.GetString("Şifre Hatırla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Password.
        /// </summary>
        internal static string Şifremi_Hatırlat {
            get {
                return ResourceManager.GetString("Şifremi Hatırlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Temizle {
            get {
                return ResourceManager.GetString("Temizle", resourceCulture);
            }
        }
    }
}
