//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace neoStockMaster.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Turkish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Turkish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("neoStockMaster.Languages.Turkish", typeof(Turkish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgilerimi Hatırlat.
        /// </summary>
        internal static string Bilgilerimi_Hatırlat {
            get {
                return ResourceManager.GetString("Bilgilerimi Hatırlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil.
        /// </summary>
        internal static string Dil {
            get {
                return ResourceManager.GetString("Dil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Ekranı.
        /// </summary>
        internal static string Giriş_Ekranı {
            get {
                return ResourceManager.GetString("Giriş Ekranı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        internal static string Giriş_Yap {
            get {
                return ResourceManager.GetString("Giriş Yap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Hatırla.
        /// </summary>
        internal static string ID_Hatırla {
            get {
                return ResourceManager.GetString("ID Hatırla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim.
        /// </summary>
        internal static string İsim {
            get {
                return ResourceManager.GetString("İsim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Ekranı.
        /// </summary>
        internal static string Kayıt_Ekranı {
            get {
                return ResourceManager.GetString("Kayıt Ekranı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Ol.
        /// </summary>
        internal static string Kayıt_Ol {
            get {
                return ResourceManager.GetString("Kayıt Ol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod.
        /// </summary>
        internal static string Kod {
            get {
                return ResourceManager.GetString("Kod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Bilgileri.
        /// </summary>
        internal static string Kullanıcı_Bilgileri {
            get {
                return ResourceManager.GetString("Kullanıcı Bilgileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        internal static string Kullanıcı_İsmi {
            get {
                return ResourceManager.GetString("Kullanıcı İsmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Onaylama.
        /// </summary>
        internal static string Kullanıcı_Onaylama {
            get {
                return ResourceManager.GetString("Kullanıcı Onaylama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Şifresi.
        /// </summary>
        internal static string Kullanıcı_Şifresi {
            get {
                return ResourceManager.GetString("Kullanıcı Şifresi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        internal static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onayla.
        /// </summary>
        internal static string Onayla {
            get {
                return ResourceManager.GetString("Onayla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        internal static string Şifre {
            get {
                return ResourceManager.GetString("Şifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Hatırla.
        /// </summary>
        internal static string Şifre_Hatırla {
            get {
                return ResourceManager.GetString("Şifre Hatırla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temizle.
        /// </summary>
        internal static string Temizle {
            get {
                return ResourceManager.GetString("Temizle", resourceCulture);
            }
        }
    }
}
